server:
  port: 8081

spring:
  cloud:
    gateway:
      routes:
        - id: route1
          uri: http://localhost:8080
          predicates:
            - Path=/demo
          filters:
            - SetPath=/customers
        - id: route2
          uri: http://localhost:8080
          predicates:
            - Path=/demo/customers/{segment}
          filters:
            - RewritePath=/demo/customers/?(?<segment>.*), /customers/$\{segment}
